In [ ]:
#RNN의 기초적인 의사코드
state_t = 0 # 초기 상태벡터
for input_t in input_sequnece:
    output_t = f(input_t, state_t)
    state_t = output_t 
    
##### 좀더 자세히 나타내자면
state_t = 0 
for input_t in input_sequence:
    output_t = activation(dot(W, input_t)+dot(U, state_t)+ b)
    state_t = output_t

In [5]:
np.random.random((2,))

array([0.42337284, 0.44713582])

In [30]:
import numpy as np

timesteps = 100
input_features =32
output_features = 64

# 입력데이터 (난수) 100개의 타입스탭마다 input_features 개수 만큼의 벡터
inputs = np.random.random((timesteps, input_features)) 
state_t = np.zeros((output_features))

print(inputs)

W = np.random.random((output_features, input_features))
U = np.random.random((output_features, output_features))
b = np.random.random((output_features,))
print(W)
successive_outputs = []
for input_t in inputs:
    output_t = np.tanh(np.dot(W, input_t) + np.dot(U, state_t) + b)
    successive_outputs.append(output_t)
    state_t = output_t
    
final_output_sequence = np.stack(successive_outputs, axis=0)

print(len(final_output_sequence))

[[3.55108285e-03 9.36741748e-01 7.45456769e-01 ... 9.82903665e-01
  2.10940404e-01 7.80100732e-01]
 [6.39059559e-01 2.99515974e-01 4.85317719e-01 ... 4.88382874e-01
  7.23117782e-01 9.36733156e-01]
 [2.91534146e-01 7.49268648e-01 6.86413795e-01 ... 8.74244303e-01
  1.51420262e-02 5.11111681e-01]
 ...
 [9.87169190e-01 8.53194843e-01 1.57729333e-01 ... 9.83823541e-01
  1.78793440e-01 8.20237368e-01]
 [2.77675907e-01 2.82778419e-01 4.33233905e-02 ... 5.09938985e-01
  4.10544098e-04 4.61036984e-01]
 [9.25763339e-01 6.73488585e-01 1.74032407e-02 ... 4.03735712e-01
  4.67699551e-01 3.29761083e-02]]
[[0.72929661 0.04212517 0.11617315 ... 0.66653086 0.83010773 0.01143713]
 [0.09053887 0.36250886 0.44664435 ... 0.80479635 0.24411946 0.37247099]
 [0.27235309 0.67537683 0.86527018 ... 0.94133897 0.30673421 0.19378684]
 ...
 [0.61589283 0.59696451 0.11237675 ... 0.62919902 0.10977021 0.02693201]
 [0.20370251 0.32591445 0.99339398 ... 0.40793618 0.67299056 0.29455725]
 [0.45198609 0.66863834 0.3123

In [29]:
from keras.layers import SimpleRNN, Embedding
from keras.models import Sequential

model = Sequential()
model.add(Embedding(10000, 32))
model.add(SimpleRNN(32))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, None, 32)          320000    
_________________________________________________________________
simple_rnn_3 (SimpleRNN)     (None, 32)                2080      
Total params: 322,080
Trainable params: 322,080
Non-trainable params: 0
_________________________________________________________________


In [33]:
model = Sequential()
model.add(Embedding(10000, 32))
model.add(SimpleRNN(32, return_sequences=True))
model.add(SimpleRNN(32, return_sequences=True))
model.add(SimpleRNN(32, return_sequences=True))
model.add(SimpleRNN(32))
model.summary()

from keras.datasets import imdb
from keras.preprocessing import sequence

max_features = 10000
maxlen = 500
batch_size = 32

(input_train, y_train), (input_test, y_test) = imdb.load_data(num_words = max_features)
print(len(input_train), '훈련 시퀀스')
print(len(input_test), '테스트 시퀀스')

print('시퀀스 패딩(Samples x time)')
input_train = sequence.pad_sequences(input_train, maxlen=maxlen)
input_test = sequence.pad_sequences(input_test, maxlen=maxlen)

print('input train 크기:', input_train.shape)
print('input test 크기:', input_test.shape)



_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_6 (Embedding)      (None, None, 32)          320000    
_________________________________________________________________
simple_rnn_12 (SimpleRNN)    (None, None, 32)          2080      
_________________________________________________________________
simple_rnn_13 (SimpleRNN)    (None, None, 32)          2080      
_________________________________________________________________
simple_rnn_14 (SimpleRNN)    (None, None, 32)          2080      
_________________________________________________________________
simple_rnn_15 (SimpleRNN)    (None, 32)                2080      
Total params: 328,320
Trainable params: 328,320
Non-trainable params: 0
_________________________________________________________________
25000 훈련 시퀀스
25000 테스트 시퀀스
시퀀스 패딩(Samples x time)
input train 크기: (25000, 500)
input test 크기: (25000, 500)


In [36]:
from keras.layers import Dense

model = Sequential()
model.add(Embedding(max_features, 32))
model.add(SimpleRNN(32))
model.add(Dense(1, activation = 'sigmoid'))

model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['acc'])
history = model.fit(input_train, y_train, epochs=10, batch_size = 128, validation_split=0.2)





Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

Train on 20000 samples, validate on 5000 samples
Epoch 1/10
20000/20000 [==============================] - 28s 1ms/step - loss: 0.6410 - acc: 0.6111 - val_loss: 0.4929 - val_acc: 0.8006
Epoch 2/10
20000/20000 [==============================] - 27s 1ms/step - loss: 0.4068 - acc: 0.8269 - val_loss: 0.4518 - val_acc: 0.7934
Epoch 3/10
20000/20000 [==============================] - 28s 1ms/step - loss: 0.2923 - acc: 0.8819 - val_loss: 0.3294 - val_acc: 0.8664
Epoch 4/10
20000/20000 [==============================] - 27s 1ms/step - loss: 0.2268 - acc: 0.9132 - val_loss: 0.3790 - val_acc: 0.8480
Epoch 5/10
20000/20000 [==============================] - 27s 1ms/step - loss: 0.1718 - acc: 0.9376 - val_loss: 0.3536 - val_acc: 0.8758
Epoch 6/10
20000/20000 [==============================] - 27s 1ms/step - loss: 0.1275 - acc: 0.9560 - val_loss: 0.3683 - val_acc: 0.8642
Epoch 7/10
20000/20000 [========

In [7]:

from keras.datasets import imdb
from keras.preprocessing import sequence

max_features = 10000
maxlen = 500
batch_size = 32

(input_train, y_train), (input_test, y_test) = imdb.load_data(num_words = max_features)
print(len(input_train), '훈련 시퀀스')
print(len(input_test), '테스트 시퀀스')

print('시퀀스 패딩(Samples x time)')
input_train = sequence.pad_sequences(input_train, maxlen=maxlen)
input_test = sequence.pad_sequences(input_test, maxlen=maxlen)

print('input train 크기:', input_train.shape)
print('input test 크기:', input_test.shape)

from keras.layers import LSTM, Embedding, Dense
from keras.models import Sequential

model = Sequential()
model.add(Embedding(max_features, 32))
model.add(LSTM(32))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['acc'])

history = model.fit(input_train, y_train, epochs=10, batch_size=128, validation_split=0.2)


25000 훈련 시퀀스
25000 테스트 시퀀스
시퀀스 패딩(Samples x time)
input train 크기: (25000, 500)
input test 크기: (25000, 500)
Train on 20000 samples, validate on 5000 samples
Epoch 1/10
20000/20000 [==============================] - 95s 5ms/step - loss: 0.4992 - acc: 0.7688 - val_loss: 0.3462 - val_acc: 0.8614
Epoch 2/10
20000/20000 [==============================] - 93s 5ms/step - loss: 0.2961 - acc: 0.8835 - val_loss: 0.2964 - val_acc: 0.8746
Epoch 3/10
20000/20000 [==============================] - 93s 5ms/step - loss: 0.2392 - acc: 0.9093 - val_loss: 0.3349 - val_acc: 0.8694
Epoch 4/10
20000/20000 [==============================] - 93s 5ms/step - loss: 0.2023 - acc: 0.9236 - val_loss: 0.3249 - val_acc: 0.8536
Epoch 5/10
20000/20000 [==============================] - 93s 5ms/step - loss: 0.1750 - acc: 0.9361 - val_loss: 0.2966 - val_acc: 0.8868
Epoch 6/10
20000/20000 [==============================] - 96s 5ms/step - loss: 0.1631 - acc: 0.9430 - val_loss: 0.3194 - val_acc: 0.8796
Epoch 7/10
20000/20000